services:
  - type: web
    name: linkedin-autoposter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: LINKEDIN_ACCESS_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0